export const keywords = [
    "Education",
    "Quran",
    "Tajweed",
    "Arabic",
    "How to learn the Quran easily",
    "Islamic Studies",
    "Online Courses",
    "El-Maragy",
    "El-Maragy Academy",
    "Al Bayan",
    "التعليم",
    "قرآن",
    "تجويد",
    "اللغة العربية",
    "كيف تتعلم القرآن بسهولة",
    "دراسات إسلامية",
    "دورات أونلاين",
    "البيان",
    "أكاديمية البيان",
    "تعليم إسلامي",
    "تعلم تجويد",
    "لغة عربية",
    "فقه",
    "عقيدة",
    "قرآن كريم",
    "دورات تعلم اللغة العربية قراءة وكتابة وتحدثا وقواعد النحو العربي والاملاء",
    "دورات القرآن الكريم",
    "تصحيح تلاوة",
    "حفظ القرآن الكريم",
    "الحصول على إجازة في القراءات القرآنية بأعلى الأسانيد المتصلة بالنبي صلى الله عليه وسلم",
    "تعلم التجويد",
    "دورات الدراسات الإسلامية",
    "دراسة العقيدة الإسلامية",
    "دراسة الفقه الإسلامي على المذاهب الفقيه الأربعة",
    "دراسة الحديث الشريف",
    "دراسة التفسير",
    "دراسة السيرة النبوية وقصص الأنبياء",
    "دراسة الآداب الإسلامية",
    "Arabic language learning courses (reading, writing, speaking, grammar, and spelling)",
    "Quran courses",
    "Quran recitation correction",
    "Quran memorization",
    "Obtaining an Ijazah in Quranic readings with the highest connected chains to the Prophet (PBUH)",
    "Learning Tajweed",
    "Islamic studies courses",
    "Studying Islamic creed (Aqeedah)",
    "Studying Islamic jurisprudence according to the four schools of thought",
    "Studying Hadith",
    "Studying Tafsir (Quran interpretation)",
    "Studying the prophetic biography (Seerah) and the stories of the prophets",
    "Studying Islamic manners"
  ];
 /*  هذا العمل ارجو فيه رضا الله سبحانه وتعالي وليكون شاهد علي يوم القيامه اني سعيت لجعله فى اجمل صورة ممكنة لطمئنه الناس للكادمية لدفع اولادهم لحفظ القران بمبلغ من المال اقل من اجره ولكن كتبت هذا الكلام ولا احد يراه غيرى لاذكر نفسي كلما قراته باخلاص النية فى العمل لله  */